config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :conversations, only: [:index, :show, :update]

  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :user_conversations, dependent: :destroy
  has_many :users, through: :user_conversations
  has_many :messages

  accepts_nested_attributes_for :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :conversation_id, :user_id

  after_create :broadcast_message

  def broadcast_message
    ConversationChannel.broadcast_to(self.conversation, self.as_broadcast)
  end

  def as_broadcast
    {
      conversation_id: self.conversation.id,
      sender_name: self.user.username,
      sent_at_date: self.created_at.in_time_zone.strftime("%b %-d"),
      sent_at_time: self.created_at.in_time_zone.strftime("%I:%M%p"),
      message_text: self.text
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_conversations, dependent: :destroy
  has_many :conversations, through: :user_conversations
  has_many :messages

  validates_presence_of :username
  validates_uniqueness_of :username
end

app/models/user_conversation.rb
class UserConversation < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates_presence_of :user_id, :conversation_id
  validates_uniqueness_of :user_id, scope: :conversation_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    if params[:user_id]
      @user_id = params[:user_id]
      @conversations = Conversation.joins(:user_conversations).where('user_conversations.user_id = ?', @user_id)
    else
      @conversations = Conversation.includes(user_conversations: :user).all
    end
  end

  def show
    @user_id ||= params[:user_id]
    @conversation = Conversation.includes(messages: :user).find(params[:id])
  end

  def update
    @conversation = Conversation.includes(messages: :user).find(params[:conversation][:id])
    return unless user_id = params[:conversation][:message][:user_id]
    return unless text = params[:conversation][:message][:text]
    Message.create(user_id: user_id, text: text, conversation_id: @conversation.id)
  end

  private
    def permitted_params
      params.require(:conversation).permit(:id, :user_id, message_attributes: [:user_id, :text])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  private
    def permitted_params
      params.require(:user).permit(:id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<div class="container">

<h3>Join a conversation</h3>
  <div>
    <% if @conversations.present? %>
      <% @conversations.each do |conversation| %>
      <div class="conversation-row">
        <% if @user_id.present? %>
          <%= link_to "Join", conversation_path(conversation, user_id: @user_id), class: "conversation-button btn btn-info" %>
        <% else %>
          <%= link_to "Join", conversation_path(conversation), class: "conversation-button btn btn-info" %>
        <% end %>
        <%= "Users to chat with: #{conversation.users.map(&:username).join(', ')}" %>
      </div>
      <% end %>
    <% else %>
      <div>
        You haven't been invited to any conversations yet :(
      </div>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<div>
  <div class="conversation-details" data-conversation-id="<%= @conversation.id %>"></div>

  <div class="container-sm users-table">
    <h5>Users in this chat:</h5>
    <% @conversation.users.each do |user| %>
      <%= "#{user.username}"%><%= " (You)" if @user_id == "#{user.id}" %><br>
    <% end %>
  </div>

  <div class="container-lg conversation-container">
    <div class="conversation-table-<%= @conversation.id %> conversation-table">
      <div class="messages">
        <% @conversation.messages.each do |message| %>
          <div class="message container-sm">
            <div>
              <span class="message-sender">
                <%= "#{message.user.username}"%>
              </span>
              at
              <span class="message-timestamp">
                <%= "#{message.created_at.in_time_zone.strftime("%I:%M%p")}" %> on
                <%= "#{message.created_at.in_time_zone.strftime("%b %-d")}" %>
              </span>
            </div>
            <div class="message-text"><%= message.text %></div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="chat-form">
      <%= form_for @conversation, remote: true, url: { action: "update", id: @conversation} do |f| %>
      <%= f.hidden_field :id %>
      <%= f.fields_for :message do |f| %>
        <%= f.hidden_field :user_id, value: @user_id %>
        <%= f.text_field :text, required: true, class: 'chat-input' %>
      <% end %>
      <%= f.submit "Send", class: 'btn btn-info' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="container">

<h3>Pick a username to log in:</h3>
  <div>
    <% if @users.present? %>
      <% @users.each do |user| %>
      <div class="user-row">
        <%= link_to "#{user.username}", conversations_path(user_id: user.id), class: "btn btn-info" %>
      </div>
      <% end %>
    <% else %>
      <div>
        There aren't any users yet :(
      </div>
    <% end %>
  </div>
</div>